# Generated by Django 4.1.2 on 2022-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('raza', models.CharField(max_length=100, null=True, verbose_name='Raza')),
            ],
        ),
    ]
