# Generated by Django 4.1.3 on 2022-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(default='null', upload_to='mascotas', verbose_name='mascotas'),
        ),
    ]
